spring:
  application:
    name: telemetry-service
  data:
    mongodb:
      uri: mongodb://prodmongodb:27017/telemetry

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type: INFO

kafka:
  topic:
    telemetry: telemetry-data-topic

server:
  port: 8080
